#!/usr/bin/env ruby

require 'optparse'
require 'active_support/all'
require 'json'

require_relative 'lib/grouper'

group = ''

OptionParser.new do |opts|
  opts.banner = 'Process data before output. Usage: ./process [options]'

  opts.on("-b", "--by [name|format]", "group name or time format") do |g|
    group = g
  end
end.parse!

Grouper.new(group, STDIN.tty? ? [] : ARGF.readlines).run{ |l| puts l }

