#!/usr/bin/env ruby

require 'optparse'
require 'active_support/all'
require 'json'

require_relative 'lib/grouper'

group = ''
func = :sum

OptionParser.new do |opts|
  opts.banner = 'Process data before output. Usage: ./process [options]'

  opts.on("-b", "--by [name|format]", "group name or time format") do |g|
    group = g
  end

  opts.on("-f", "--function [sum|avg|min|max]", "grouping function") do |f|
    func = f
  end
end.parse!

Grouper.new(group, STDIN.tty? ? [] : ARGF.readlines, func: func).run{ |l| puts l }

