#!/usr/bin/env ruby

require 'optparse'
require 'json'

require_relative 'lib/normalizer'

normalize = false

OptionParser.new do |opts|
  opts.banner = 'Transform data. Usage: ./transform [options]'

  opts.on("-n", "--[no-]normalize", "perform data normalization") do |n|
    normalize = n
  end
end.parse!

unless STDIN.tty?
  lines = ARGF.readlines.collect{ |l| JSON.parse(l) }

  Normalizer.new(lines).execute if normalize

  lines.each {|l| puts l.to_json }
end
